
# this is for resnet50
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/home/sharfikeg/my_files/retIQA/dc_ret/Save_TReS/'   --droplr 1 --epochs 5 --gpunum '0'  --datapath  '/home/tres/qadata/fblive'    --dataset 'fblive'   --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/home/sharfikeg/my_files/retIQA/dc_ret/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '0'  --datapath  '/home/tres/qadata/csiq'      --dataset 'csiq'     --seed 2021 --vesion 1


# OMP_NUM_THREADS=24 python /home/sharfikeg/my_files/retIQA/dc_ret/DistorsionFeatureExtractor/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/extra_disk_1/sharfikeg/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '3'  --datapath  '/extra_disk_1/sharfikeg/spaq'     --dataset 'spaq'    --seed 1 --vesion 1
# OMP_NUM_THREADS=24 python /home/sharfikeg/my_files/retIQA/dc_ret/DistorsionFeatureExtractor/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/extra_disk_1/sharfikeg/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '2'  --datapath  '/home/sharfikeg/my_files/retIQA/koniq10k'     --dataset 'koniq'    --seed 1 --vesion 1
# OMP_NUM_THREADS=24 python /home/sharfikeg/my_files/retIQA/dc_ret/DistorsionFeatureExtractor/TReS/run.py --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/extra_disk_1/sharfikeg/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '2'  --datapath  '/home/sharfikeg/my_files/retIQA/kadid10k'  --dataset 'kadid10k' --seed 1 --vesion 1
# OMP_NUM_THREADS=24 python /home/sharfikeg/my_files/retIQA/dc_ret/DistorsionFeatureExtractor/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/extra_disk_1/sharfikeg/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '2'  --datapath  '/home/s-kastryulin/data/tid2013'   --dataset 'tid2013'  --seed 1 --vesion 1
OMP_NUM_THREADS=2 python /home/sharfikeg/my_files/retIQA/ret/TReSM/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/extra_disk_1/sharfikeg/Save_TReSM/'   --droplr 1 --epochs 20 --gpunum '5'  --datapath  '/home/sharfikeg/my_files/retIQA/csiq'  --dataset 'csiq'  --seed 1 --vesion 1 --k 3 --multi_return 0 --finetune 0



# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/home/sharfikeg/my_files/retIQA/dc_ret/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '0'  --datapath  '/home/tres/qadata/live'      --dataset 'live'     --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet50' --batch_size 53  --svpath  '/home/sharfikeg/my_files/retIQA/dc_ret/Save_TReS/'   --droplr 1 --epochs 3 --gpunum '0'  --datapath  '/home/tres/qadata/clive'     --dataset 'clive'    --seed 2021 --vesion 1

# # this is for resnet34
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/clive'  --dataset 'clive' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/koniq'  --dataset 'koniq' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/fblive'  --dataset 'fblive' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/tid2013'  --dataset 'tid2013' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/kadid10k'  --dataset 'kadid10k' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/live'  --dataset 'live' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet34' --batch_size 160  --svpath  '/home/tres/Save_TReS_34/'   --droplr 2 --epochs 6 --gpunum '0'  --datapath  '/home/tres/qadata/csiq'  --dataset 'csiq' --seed 2021 --vesion 1 

# # this is for resnet18
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/clive'  --dataset 'clive' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/koniq'  --dataset 'koniq' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/fblive'  --dataset 'fblive' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/tid2013'  --dataset 'tid2013' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/kadid10k'  --dataset 'kadid10k' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/live'  --dataset 'live' --seed 2021 --vesion 1
# OMP_NUM_THREADS=1 python /home/tres/TReS/run.py  --num_encoder_layerst 2 --dim_feedforwardt 64 --nheadt 16 --network 'resnet18' --batch_size 220  --svpath  '/home/tres/hope/Save_TReS_18/'   --droplr 3 --epochs 9 --gpunum '0'  --datapath  '/home/tres/qadata/csiq'  --dataset 'csiq' --seed 2021 --vesion 1 
